services:
  - type: web
    name: qr-attendance
    runtime: go
    rootDir: QR_Attendance
    buildCommand: go build -o main .
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      - key: FIREBASE_CONFIG
        sync: false
    healthCheckPath: /login
    autoDeploy: true
